db:
  image: postgres
  
nginx:
  image: nginx
  volumes:
   - ./nginx.conf:/etc/nginx/conf.d/default.conf
   - ./ui:/app
  ports:
   - "80:80"
  links:
   - web
  restart: always
  
web:
  build: .
  environment:
    - DEBUG=1
    - HOST=0.0.0.0
    - SQLALCHEMY_DATABASE_URI=postgres://postgres@db
    - ENABLE_2FA=0
    - TOTP_DOMAIN=docker.dev
    - API_URL_PREFIX=/api
  volumes:
    - .:/code
  links:
    - db
  restart: always