db:
  image: postgres
web:
  build: .
  environment:
    - DEBUG=1
    - HOST=0.0.0.0
    - SQLALCHEMY_DATABASE_URI=postgres://postgres@db
    - ENABLE_2FA=1
    - TOTP_DOMAIN=docker.dev
  volumes:
    - .:/code
  ports:
    - "5000:5000"
  links:
    - db