sigildb-data:
  image: busybox
  command: /bin/true
  volumes: 
    - /var/lib/postgresql/data

sigildb:
  image: postgres
  volumes_from:
    - sigildb-data
  
nginx:
  image: nginx
  volumes:
   - ./nginx.conf:/etc/nginx/conf.d/default.conf
   - .:/sigil
  volumes_from:
   - sigil
  ports:
   - "80:80"
  links:
   - sigil
  
sigil:
  build: .
  environment:
    - DEBUG=yes
    - HOST=0.0.0.0
    - SQLALCHEMY_DATABASE_URI=postgres://postgres@sigildb
    - ENABLE_2FA=no
    - TOTP_DOMAIN=docker.dev
    - API_URL_PREFIX=/sigil-api
    - SESSION_TOKEN_MAX_AGE=300
    - MAIL_SUPPRESS_SEND=no
    - MAIL_SERVER=smtp-adimian.alwaysdata.net
    - MAIL_USERNAME=sigil@adimian.com
    - MAIL_PORT=587
    - MAIL_USE_TLS=yes
    - MAIL_PASSWORD=aQjRk8wDhqS5R50DrDO9
    - MAIL_DEFAULT_SENDER=sigil@adimian.com
    - UI_BASE_URL=http://docker.dev/sigil
  volumes:
    - .:/sigil
  links:
    - sigildb  