sigildb-data:
  image: busybox
  command: /bin/true
  volumes: 
    - /var/lib/postgresql/data

sigildb:
  image: postgres
  volumes_from:
    - sigildb-data
  
sigil:
  build: .
  environment:
    - DEBUG=yes
    - MAIL_TEMPLATE_FOLDER=/sigil/custom_templates
    - STANDALONE=yes
    - APPLICATION_NAME=CEEME Services
    - HOST=0.0.0.0
    - PORT=80
    - SQLALCHEMY_DATABASE_URI=postgres://postgres@sigildb
    - ENABLE_2FA=no
    - TOTP_DOMAIN=docker.dev
    - SERVE_STATIC=yes
    - UI_URL_PREFIX=/sigil
    - API_URL_PREFIX=/sigil-api
    - SESSION_TOKEN_MAX_AGE=1800
    - MAIL_SUPPRESS_SEND=no
    - MAIL_SERVER=smtp-adimian.alwaysdata.net
    - MAIL_USERNAME=sigil@adimian.com
    - MAIL_PORT=587
    - MAIL_USE_TLS=yes
    - MAIL_PASSWORD=aQjRk8wDhqS5R50DrDO9
    - MAIL_DEFAULT_SENDER=sigil@adimian.com
    - UI_BASE_URL=http://docker.dev/sigil
    - LDAP_HOST=slapd
    - LDAP_AUTO_UPDATE=yes
    - OVH_ENDPOINT=ovh-eu
    - OVH_APPLICATION_KEY=XBbhIOWmiSjT4Rie
    - OVH_APPLICATION_SECRET=t09iG14mPpMAmeFuKK0MSZYnrHJNeaiw
  volumes:
    - .:/sigil
  links:
    - sigildb 
    - slapd
  ports:
   - "80:80"
    
slapd:
  image: registry.adimian.com/slapd/extendedslapd
  environment:
    - LDAP_DOMAIN=mycorp.com
    - LDAP_ORGANISATION="My Mega Corporation"
    - LDAP_ROOTPASS=s3cr3tpassw0rd
  ports:
    - "389:389"