"""extrafield

Revision ID: 1cdde792deb
Revises: 436332d8734
Create Date: 2015-10-26 15:54:12.078819

"""

# revision identifiers, used by Alembic.
revision = '1cdde792deb'
down_revision = '436332d8734'
branch_labels = ()
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extrafield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=256), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extra_field',
    sa.Column('extrafield_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['extrafield_id'], ['extrafield.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.UniqueConstraint('extrafield_id', 'member_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extra_field')
    op.drop_table('extrafield')
    ### end Alembic commands ###
