"""add teams to groups

Revision ID: 328284d0e8
Revises: 3f74c836ee
Create Date: 2016-06-01 18:09:32.043280

"""

# revision identifiers, used by Alembic.
revision = '328284d0e8'
down_revision = '3f74c836ee'
branch_labels = ()
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_group_member',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['virtualgroup.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['userteam.id'], ),
    sa.UniqueConstraint('group_id', 'member_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_group_member')
    ### end Alembic commands ###
