"""prevent password token reuse

Revision ID: 55b0b89698b
Revises: 1cdde792deb
Create Date: 2016-03-21 14:19:17.746512

"""

# revision identifiers, used by Alembic.
revision = '55b0b89698b'
down_revision = '1cdde792deb'
branch_labels = ()
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_gen_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_gen_date')
    ### end Alembic commands ###
